apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: epb6nck3u-nodejs
  janus-idp.io/tekton: epb6nck3u-nodejs
  backstage.io/kubernetes-id: epb6nck3u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: epb6nck3u-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
